; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "App Launcher"
#define MyAppVersion "3.0"
#define MyAppPublisher "Samyak"
#define MyAppURL "https://github.com/SpaceCoderPro/App-Launcher"
#define MyAppExeName "App Launcher.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B2D0211B-6A9C-4551-BAB8-1DD84DB6AF32}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=App Launcher 3.0
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\samya\Documents\Coding Projects\App Launcher\App Launcher\Cook for App\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\samya\Documents\Coding Projects\App Launcher\App Launcher\Cook for App\dist\Full Calculator Fast.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\samya\Documents\Coding Projects\App Launcher\App Launcher\Cook for App\dist\index.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\samya\Documents\Coding Projects\App Launcher\App Launcher\Cook for App\dist\puppy.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\samya\Documents\Coding Projects\App Launcher\App Launcher\Cook for App\dist\Simple Fast Calculator.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\samya\Documents\Coding Projects\App Launcher\App Launcher\Cook for App\dist\Simple Int Calculator.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

